# Generated by Django 4.1.7 on 2023-02-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=255)),
                ('loc', models.CharField(max_length=255)),
                ('m_name', models.CharField(max_length=255)),
                ('s_year', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=10)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
