# Generated by Django 4.1.7 on 2023-02-26 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_cprofile_pic1_cprofile_pic2_cprofile_pic3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(max_length=10)),
                ('c_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.cprofile')),
            ],
        ),
    ]
