# Generated by Django 4.1.7 on 2023-06-08 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobno', models.IntegerField(max_length=10)),
                ('loc', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.cprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
