# Generated by Django 4.1.7 on 2023-06-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_booking_delete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='mobno',
            field=models.IntegerField(),
        ),
    ]
