# Generated by Django 4.1.7 on 2023-06-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_alter_booking_mobno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_id', models.CharField(max_length=10)),
                ('plot_area', models.DecimalField(decimal_places=2, max_digits=6)),
                ('type', models.CharField(max_length=30)),
                ('sqft', models.IntegerField()),
                ('water', models.CharField(max_length=30)),
                ('location', models.URLField()),
                ('requirement', models.TextField(max_length=500)),
                ('budget', models.IntegerField()),
            ],
        ),
    ]
