# Generated by Django 4.1.7 on 2023-06-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='water',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
    ]
