# Generated by Django 4.1.7 on 2023-06-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_alter_requirements_water'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='type',
            field=models.CharField(choices=[('1', 'Single Storied'), ('2', 'Double Storied')], max_length=1),
        ),
    ]
