# Generated by Django 4.1.7 on 2023-06-18 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0010_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='proj_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
