# Generated by Django 4.1.7 on 2023-06-23 07:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0011_booking_proj_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='uname',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
