# Generated by Django 4.1.7 on 2023-07-04 04:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0012_requirements_uname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirements',
            name='water',
        ),
        migrations.AddField(
            model_name='requirements',
            name='place',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
