# Generated by Django 4.1.7 on 2023-07-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0016_alter_requirements_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='type',
            field=models.CharField(choices=[('Single_Normal', 'Single Storied - Normal'), ('Double_Normal', 'Double Storied - Normal'), ('Traditional', 'Traditional Kerala Design'), ('Colonial', 'Colonial Architecture'), ('Dutch', 'Dutch Architecture'), ('Modern', 'Modern')], max_length=40),
        ),
    ]
