# Generated by Django 4.1.7 on 2023-07-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0017_alter_requirements_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='type',
            field=models.CharField(choices=[('Single_Normal', 'Single Storied - Normal'), ('Double_Normal', 'Double Storied - Normal'), ('Modern_Style', 'Modern Architecture'), ('Traditional_Style', 'Traditional Kerala Architecture'), ('Colonial_Style', 'Colonial Architecture'), ('Dutch_Style', 'Dutch Architecture'), ('Victorian_Style', 'Victorian Architecture')], max_length=40),
        ),
    ]
