# Generated by Django 4.1.7 on 2023-08-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0018_alter_requirements_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cprofile',
            name='dom',
            field=models.CharField(choices=[('Designing', 'Designing'), ('Builder', 'Builder'), ('Designing And Building', 'Designing And Building')], default='Designing And Building', max_length=50),
            preserve_default=False,
        ),
    ]
