# Generated by Django 4.1.7 on 2023-07-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_purchase_bookid_purchase_dtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='bookid',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='dtime',
            field=models.DateTimeField(),
        ),
    ]
