# Generated by Django 4.1.7 on 2023-07-31 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_products_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='items',
            field=models.TextField(default='items', max_length=500),
            preserve_default=False,
        ),
    ]
